sban:
  sbanDescrCMD: "§asuper ban player"
  sbanUsageCMD: "§cUsage: §7/sban <player> <reason>"
  spardonDescrCMD: "pardon player"
  spardonUsageCMD: "§cUsage: §7/spardon"
  banMessage: "You have success banned player %p%"
  pardonMessage: "You have success pardoned player %p%"
  reasonBan: "\n§r§6You, §a%tg% §f, §chave been blocked on the server\n§r§fReasоn: §6%reason%\n§r§6pardon is blocked\n§r§frules: §3link"
  playerNotFound: "Player %p% not found"
